server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: library-system
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/library
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 465
    username: helios.email.test@gmail.com
    password: ltuzwzyrvvhpxjrt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            required: true

app:
  register-otp:
    quota: 5
    wrong-quota: 3
    resend-quota: 3
    expiration-time: 3600
  verify-otp:
    quota: 5
    wrong-quota: 3
    resend-quota: 3
    expiration-time: 3600
  password-rsa:
    private-key: rsa/private_key.der
    public-key: rsa/public_key.der
  token-rsa:
    private-key: rsa/private_key.der
    public-key: rsa/public_key.der
  access-token:
    active-time: 36000
    issuer: hieplp.dev
  refresh-token:
    active-time: 864000
    issuer: hieplp.dev
